/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingmanagement.gui.user;

/**
 *
 * @author guruv
 */

import busbookingmanagement.dao.BusDAO;
import busbookingmanagement.gui.user.UserDashboard;
import busbookingmanagement.gui.user.RegisterFrame;
import javax.swing.JOptionPane;
import busbookingmanagement.util.Session;
import java.sql.*;

public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        welcomLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerContactlbl = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        mailLabel = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        psswdLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(153, 204, 255));
        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.setPreferredSize(new java.awt.Dimension(656, 70));
        topPanel.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoLabel.setText("Logo");
        topPanel.add(logoLabel, java.awt.BorderLayout.WEST);

        welcomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomLabel.setText("Welcome To My Bus");
        topPanel.add(welcomLabel, java.awt.BorderLayout.CENTER);

        bgPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        footerPanel.setBackground(new java.awt.Color(153, 204, 255));
        footerPanel.setPreferredSize(new java.awt.Dimension(676, 70));

        footerContactlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        footerContactlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerContactlbl.setText("contact@mybus.com");
        footerPanel.add(footerContactlbl);

        bgPanel.add(footerPanel, java.awt.BorderLayout.SOUTH);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setPreferredSize(new java.awt.Dimension(656, 560));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setPreferredSize(new java.awt.Dimension(350, 150));
        formPanel.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        mailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mailLabel.setText("Email");
        formPanel.add(mailLabel);
        formPanel.add(txtemail);

        psswdLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        psswdLabel.setText("Password");
        formPanel.add(psswdLabel);
        formPanel.add(jPasswordField1);

        loginBtn.setText("Login");
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        formPanel.add(loginBtn);

        registerBtn.setText("Register");
        registerBtn.addActionListener(this::registerBtnActionPerformed);
        formPanel.add(registerBtn);

        centerPanel.add(formPanel, new java.awt.GridBagConstraints());

        bgPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String email = txtemail.getText();
        String pass = new String(jPasswordField1.getPassword());
        if(email.isEmpty() || pass.isEmpty()){
    
            JOptionPane.showMessageDialog(this,"Please fill all fields");
            return;
        }

        BusDAO dao = new BusDAO();

        try{

            ResultSet rs = dao.userLogin(email, pass);

            if(rs.next()){

                Session.currentUserId = rs.getInt("CustID");
                Session.currentUserName = rs.getString("Name");

                JOptionPane.showMessageDialog(this,"Login Successful");

                new UserDashboard().setVisible(true);
                dispose();

            }else{

                JOptionPane.showMessageDialog(this,"Invalid Email or Password");

            }

        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        new RegisterFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel footerContactlbl;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JLabel psswdLabel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtemail;
    private javax.swing.JLabel welcomLabel;
    // End of variables declaration//GEN-END:variables
}
