/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingmanagement.gui.user;

/**
 *
 * @author guruv
 */

import busbookingmanagement.dao.BusDAO;
import busbookingmanagement.gui.user.LoginFrame;
import javax.swing.JOptionPane;

public class RegisterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFrame.class.getName());

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        welcomLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerContactlbl = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        mailLabel = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        psswdLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPh = new javax.swing.JTextField();
        sbmtBtn = new javax.swing.JButton();
        loginPage = new javax.swing.JButton();
        clrBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(153, 204, 255));
        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.setPreferredSize(new java.awt.Dimension(656, 70));
        topPanel.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoLabel.setText("Logo");
        topPanel.add(logoLabel, java.awt.BorderLayout.WEST);

        welcomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomLabel.setText("Welcome To My Bus User Registration");
        topPanel.add(welcomLabel, java.awt.BorderLayout.CENTER);

        bgPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        footerPanel.setBackground(new java.awt.Color(153, 204, 255));
        footerPanel.setPreferredSize(new java.awt.Dimension(676, 70));

        footerContactlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        footerContactlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerContactlbl.setText("contact@mybus.com");
        footerPanel.add(footerContactlbl);

        bgPanel.add(footerPanel, java.awt.BorderLayout.SOUTH);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setPreferredSize(new java.awt.Dimension(656, 560));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setPreferredSize(new java.awt.Dimension(350, 200));
        formPanel.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        mailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mailLabel.setText("Email");
        formPanel.add(mailLabel);

        txtmail.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        formPanel.add(txtmail);

        psswdLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        psswdLabel.setText("Password");
        formPanel.add(psswdLabel);
        formPanel.add(jPasswordField1);

        jLabel2.setText("Name");
        formPanel.add(jLabel2);
        formPanel.add(txtName);

        jLabel3.setText("Phone Number");
        formPanel.add(jLabel3);
        formPanel.add(txtPh);

        sbmtBtn.setText("Submit");
        sbmtBtn.addActionListener(this::sbmtBtnActionPerformed);
        formPanel.add(sbmtBtn);

        loginPage.setText("Back");
        loginPage.addActionListener(this::loginPageActionPerformed);
        formPanel.add(loginPage);

        clrBtn.setText("Clear");
        clrBtn.addActionListener(this::clrBtnActionPerformed);
        formPanel.add(clrBtn);

        centerPanel.add(formPanel, new java.awt.GridBagConstraints());

        bgPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbmtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtBtnActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String email = txtmail.getText();
        String phone = txtPh.getText();
        String pass = new String(jPasswordField1.getPassword());

        if(name.isEmpty() || email.isEmpty() || phone.isEmpty() || pass.isEmpty()){

            JOptionPane.showMessageDialog(this,"Please fill all fields");
            return;
        }

        BusDAO dao = new BusDAO();

        try{

            dao.createCustAcc(name,email,phone,pass);

            JOptionPane.showMessageDialog(this,"Registration Successful");

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_sbmtBtnActionPerformed

    private void loginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPageActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_loginPageActionPerformed

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtmail.setText("");
        txtPh.setText("");
        jPasswordField1.setText("");
        txtName.requestFocus();
    }//GEN-LAST:event_clrBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton clrBtn;
    private javax.swing.JLabel footerContactlbl;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginPage;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JLabel psswdLabel;
    private javax.swing.JButton sbmtBtn;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPh;
    private javax.swing.JTextField txtmail;
    private javax.swing.JLabel welcomLabel;
    // End of variables declaration//GEN-END:variables
}
