/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingmanagement.gui.user;

/**
 *
 * @author guruv
 */
import busbookingmanagement.gui.user.LoginFrame;
import javax.swing.JOptionPane;
import busbookingmanagement.util.Session;

public class UserDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
        welcomLabel.setText("Welcome " + Session.currentUserName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        welcomLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerContactlbl = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        bookTicket = new javax.swing.JButton();
        viewTicket = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(153, 204, 255));
        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.setPreferredSize(new java.awt.Dimension(656, 70));
        topPanel.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoLabel.setText("Logo");
        topPanel.add(logoLabel, java.awt.BorderLayout.WEST);

        welcomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomLabel.setText("User Dash Board");
        topPanel.add(welcomLabel, java.awt.BorderLayout.CENTER);

        bgPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        footerPanel.setBackground(new java.awt.Color(153, 204, 255));
        footerPanel.setPreferredSize(new java.awt.Dimension(676, 70));

        footerContactlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        footerContactlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerContactlbl.setText("contact@mybus.com");
        footerPanel.add(footerContactlbl);

        bgPanel.add(footerPanel, java.awt.BorderLayout.SOUTH);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setPreferredSize(new java.awt.Dimension(656, 560));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setPreferredSize(new java.awt.Dimension(350, 200));
        formPanel.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        bookTicket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookTicket.setForeground(new java.awt.Color(255, 102, 102));
        bookTicket.setText("BookTicket");
        bookTicket.addActionListener(this::bookTicketActionPerformed);
        formPanel.add(bookTicket);

        viewTicket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewTicket.setForeground(new java.awt.Color(255, 102, 102));
        viewTicket.setText("ViewTicket");
        viewTicket.addActionListener(this::viewTicketActionPerformed);
        formPanel.add(viewTicket);

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("LogOut");
        logout.addActionListener(this::logoutActionPerformed);
        formPanel.add(logout);

        centerPanel.add(formPanel, new java.awt.GridBagConstraints());

        bgPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketActionPerformed
        // TODO add your handling code here:
        new BusList().setVisible(true);
        dispose();

    }//GEN-LAST:event_bookTicketActionPerformed

    private void viewTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketActionPerformed
        // TODO add your handling code here:
        new ViewTickets().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_viewTicketActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout",
        JOptionPane.YES_NO_OPTION
        );

        if(choice == JOptionPane.YES_OPTION){
            
            Session.currentUserId = 0;
            Session.currentUserName = null;
            
            new LoginFrame().setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton bookTicket;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel footerContactlbl;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logout;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton viewTicket;
    private javax.swing.JLabel welcomLabel;
    // End of variables declaration//GEN-END:variables
}
