/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mongoproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AcademicScores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AcademicScores.class.getName());

    /**
     * Creates new form AcademicScores
     */
    public AcademicScores() {
        initComponents();
        loadResults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        orderBtn = new javax.swing.JToggleButton();
        btnupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Kannada", "English", "Maths", "Science", "Social", "Percentage", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultTable);

        jButton2.setText("BACK");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        orderBtn.setText("ASC | DEC");
        orderBtn.addActionListener(this::orderBtnActionPerformed);

        btnupdate.setText("Update");
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(orderBtn)
                        .addGap(58, 58, 58)
                        .addComponent(btnupdate)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(orderBtn)
                    .addComponent(btnupdate))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ViewStudents().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
         try{
            var database = MongoConfig.getDatabase();
            var collection = database.getCollection("results");

            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) resultTable.getModel();

            model.setRowCount(0);

            var studentsCollection = database.getCollection("Students");

            int order;

            if(orderBtn.isSelected()){
                order = -1; // Descending
            }else{
                order = 1;  // Ascending
            }

            var docs = collection.find()
                    .sort(new org.bson.Document("percentage", order));

            for(org.bson.Document doc : docs){

                int id = doc.getInteger("id");

                org.bson.Document student =
                        studentsCollection.find(new org.bson.Document("id", id)).first();

                String name = "";
                if(student != null){
                    name = student.getString("name");
                }

                int kannada = doc.getInteger("kannada");
                int engl = doc.getInteger("english");
                int maths = doc.getInteger("maths");
                int sci = doc.getInteger("science");
                int soc = doc.getInteger("social");

                Number percentNum = (Number) doc.get("percentage");
                double percent = percentNum.doubleValue();
                String grade = doc.getString("grade");

                model.addRow(new Object[]{id,name,kannada,engl,maths,sci,soc,percent,grade});
            }

        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"Error "+e.getMessage());
        }
    }//GEN-LAST:event_orderBtnActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
         // TODO add your handling code here:
         int row = resultTable.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        int id = (int) resultTable.getValueAt(row, 0);
        int currentkannada = (int) resultTable.getValueAt(row, 2);
        int currentenglish =(int) resultTable.getValueAt(row, 3);
        int currentmaths = (int) resultTable.getValueAt(row,4);
        int currentsci = (int) resultTable.getValueAt(row, 5);
        int currentsocial = (int) resultTable.getValueAt(row, 6);

        try {
            
            int newkannada = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Enter Marks for Kannada", currentkannada));
            int neweng = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Enter English Marks", currentenglish));
            int newmath = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Enter Maths Marks", currentmaths));
            int newsci = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Enter Science Marks", currentsci));
            int newsocial = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Enter Social Marks", currentsocial));
            
            double percentage = (newkannada + neweng + newmath + newsci + newsocial) / 5.0;

            String grade;

            if(percentage >= 90)
                grade = "A+";
            else if(percentage >= 80)
                grade = "A";
            else if(percentage >= 70)
                grade = "B";
            else if(percentage >= 60)
                grade = "C";
            else if(percentage >= 50)
                grade = "D";
            else
                grade = "Fail";

            var database = MongoConfig.getDatabase();
            var collection = database.getCollection("results");

            org.bson.Document filter = new org.bson.Document("id", id);

            org.bson.Document update = new org.bson.Document("$set",
                    new org.bson.Document("kannada", newkannada)
                            .append("english", neweng)
                            .append("maths", newmath)
                            .append("science", newsci)
                            .append("social", newsocial)
                            .append("percentage", percentage)
                            .append("grade", grade));

            collection.updateOne(
                    filter,
                    update,
                    new com.mongodb.client.model.UpdateOptions().upsert(true)
            );

            javax.swing.JOptionPane.showMessageDialog(this, "Updated Successfully");

            loadResults(); // refresh table

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }    
    }//GEN-LAST:event_btnupdateActionPerformed

    private void loadResults(){
         try{

            var database = MongoConfig.getDatabase();
            var resultsCollection = database.getCollection("results");
            var studentsCollection = database.getCollection("Students");

            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) resultTable.getModel();

            model.setRowCount(0);

            var students = studentsCollection.find();

            for(org.bson.Document student : students){

                int id = student.getInteger("id");
                String name = student.getString("name");

                org.bson.Document result =
                        resultsCollection.find(new org.bson.Document("id", id)).first();

                int kannada = 0;
                int engl = 0;
                int maths = 0;
                int sci = 0;
                int soc = 0;
                double percent = 0;
                String grade = "";

                if(result != null){
                    kannada = result.getInteger("kannada");
                    engl = result.getInteger("english");
                    maths = result.getInteger("maths");
                    sci = result.getInteger("science");
                    soc = result.getInteger("social");

                    Number percentNum = (Number) result.get("percentage");
                    percent = percentNum.doubleValue();

                    grade = result.getString("grade");
                }

                model.addRow(new Object[]{id,name,kannada,engl,maths,sci,soc,percent,grade});
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error "+e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AcademicScores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton orderBtn;
    private javax.swing.JTable resultTable;
    // End of variables declaration//GEN-END:variables
}
